language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"

install:
  - npm install -g gulp
  - npm install -g typescript
  - npm install -g remap-istanbul
  - npm install -g coveralls
  - npm install

script: gulp put-coveralls
